/*
 * Trading API
 * Alpaca's Trading API is a modern platform for algorithmic trading.
 *
 * The version of the OpenAPI document: 2.0.1
 * Contact: support@alpaca.markets
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package net.jacobpeterson.alpaca.openapi.trader.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import java.util.function.Predicate;
import com.google.gson.TypeAdapter;
import com.google.gson.JsonElement;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * - FILL   Order fills (both partial and full fills)  - TRANS   Cash transactions (both CSD and CSW)  - MISC   Miscellaneous or rarely used activity types (All types except those in TRANS, DIV, or FILL)  - ACATC   ACATS IN/OUT (Cash)  - ACATS   ACATS IN/OUT (Securities)  - CFEE   Crypto fee  - CSD   Cash deposit(+)  - CSW   Cash withdrawal(-)  - DIV   Dividends  - DIVCGL   Dividend (capital gain long term)  - DIVCGS   Dividend (capital gain short term)  - DIVFEE   Dividend fee  - DIVFT   Dividend adjusted (Foreign Tax Withheld)  - DIVNRA   Dividend adjusted (NRA Withheld)  - DIVROC   Dividend return of capital  - DIVTW   Dividend adjusted (Tefra Withheld)  - DIVTXEX   Dividend (tax exempt)  - FEE   Fee denominated in USD  - INT   Interest (credit/margin)  - INTNRA   Interest adjusted (NRA Withheld)  - INTTW   Interest adjusted (Tefra Withheld)  - JNL   Journal entry  - JNLC   Journal entry (cash)  - JNLS   Journal entry (stock)  - MA   Merger/Acquisition  - NC   Name change  - OPASN   Option assignment  - OPEXC   Option exercise  - OPEXP   Option expiration  - OPTRD   Option trade  - PTC   Pass Thru Charge  - PTR   Pass Thru Rebate  - REORG   Reorg CA  - SC   Symbol change  - SSO   Stock spinoff  - SSP   Stock split
 */
@JsonAdapter(ActivityType.Adapter.class)
public enum ActivityType {
  
  FILL("FILL"),
  
  TRANS("TRANS"),
  
  MISC("MISC"),
  
  ACATC("ACATC"),
  
  ACATS("ACATS"),
  
  CSD("CSD"),
  
  CSW("CSW"),
  
  DIV("DIV"),
  
  DIVCGL("DIVCGL"),
  
  DIVCGS("DIVCGS"),
  
  DIVFEE("DIVFEE"),
  
  DIVFT("DIVFT"),
  
  DIVNRA("DIVNRA"),
  
  DIVROC("DIVROC"),
  
  DIVTW("DIVTW"),
  
  DIVTXEX("DIVTXEX"),
  
  INT("INT"),
  
  INTNRA("INTNRA"),
  
  INTTW("INTTW"),
  
  JNL("JNL"),
  
  JNLC("JNLC"),
  
  JNLS("JNLS"),
  
  MA("MA"),
  
  NC("NC"),
  
  OPASN("OPASN"),
  
  OPEXC("OPEXC"),
  
  OPEXP("OPEXP"),
  
  OPTRD("OPTRD"),
  
  PTC("PTC"),
  
  PTR("PTR"),
  
  REORG("REORG"),
  
  SC("SC"),
  
  SSO("SSO"),
  
  SSP("SSP"),
  
  CFEE("CFEE"),
  
  FEE("FEE");

  private String value;

  ActivityType(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static ActivityType fromValue(String value) {
    for (ActivityType b : ActivityType.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    return null;
  }

  public static class Adapter extends TypeAdapter<ActivityType> {
    @Override
    public void write(final JsonWriter jsonWriter, final ActivityType enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public ActivityType read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return ActivityType.fromValue(value);
    }
  }

  public static boolean validate = false;
    public static Predicate<JsonElement> isValid = jsonElement -> true;
    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (!isValid.test(jsonElement)) throw new RuntimeException();
      if (!validate) return;

    String value = jsonElement.getAsString();
    ActivityType.fromValue(value);
  }
}

