/*
 * Trading API
 * Alpaca's Trading API is a modern platform for algorithmic trading.
 *
 * The version of the OpenAPI document: 2.0.1
 * Contact: support@alpaca.markets
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package net.jacobpeterson.alpaca.openapi.trader.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import java.util.function.Predicate;
import com.google.gson.TypeAdapter;
import com.google.gson.JsonElement;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Represents which side this order was on:  - buy - sell
 */
@JsonAdapter(OrderSide.Adapter.class)
public enum OrderSide {
  
  BUY("buy"),
  
  SELL("sell");

  private String value;

  OrderSide(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static OrderSide fromValue(String value) {
    for (OrderSide b : OrderSide.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    return null;
  }

  public static class Adapter extends TypeAdapter<OrderSide> {
    @Override
    public void write(final JsonWriter jsonWriter, final OrderSide enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public OrderSide read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return OrderSide.fromValue(value);
    }
  }

  public static boolean validate = false;
    public static Predicate<JsonElement> isValid = jsonElement -> true;
    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (!isValid.test(jsonElement)) throw new RuntimeException();
      if (!validate) return;

    String value = jsonElement.getAsString();
    OrderSide.fromValue(value);
  }
}

