/*
 * Broker API
 * Open brokerage accounts, enable stock, options and crypto trading. Manage the ongoing user experience and brokerage customer lifecycle with the Alpaca Broker API
 *
 * The version of the OpenAPI document: 1.1.1
 * Contact: support@alpaca.markets
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package net.jacobpeterson.alpaca.openapi.broker.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.function.Predicate;
import java.util.Arrays;
import net.jacobpeterson.alpaca.openapi.broker.model.AdminActionCreatedByKind;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.function.Predicate;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import net.jacobpeterson.alpaca.openapi.broker.JSON;

/**
 * Represents structure of an Creator&#39;s Identifier for all AdminAction type 
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-03-23T18:58:47.485165-07:00[America/Los_Angeles]")
public class AdminActionCreatedBy {
  public static final String SERIALIZED_NAME_KIND = "kind";
  @SerializedName(SERIALIZED_NAME_KIND)
  private AdminActionCreatedByKind kind;

  public static final String SERIALIZED_NAME_ID_REFERENCE = "id_reference";
  @SerializedName(SERIALIZED_NAME_ID_REFERENCE)
  private String idReference;

  public AdminActionCreatedBy() {
  }

  public AdminActionCreatedBy kind(AdminActionCreatedByKind kind) {
    this.kind = kind;
    return this;
  }

   /**
   * Get kind
   * @return kind
  **/
  @javax.annotation.Nullable
  public AdminActionCreatedByKind getKind() {
    return kind;
  }

  public void setKind(AdminActionCreatedByKind kind) {
    this.kind = kind;
  }


  public AdminActionCreatedBy idReference(String idReference) {
    this.idReference = idReference;
    return this;
  }

   /**
   * Get idReference
   * @return idReference
  **/
  @javax.annotation.Nullable
  public String getIdReference() {
    return idReference;
  }

  public void setIdReference(String idReference) {
    this.idReference = idReference;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AdminActionCreatedBy adminActionCreatedBy = (AdminActionCreatedBy) o;
    return Objects.equals(this.kind, adminActionCreatedBy.kind) &&
        Objects.equals(this.idReference, adminActionCreatedBy.idReference);
  }

  @Override
  public int hashCode() {
    return Objects.hash(kind, idReference);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AdminActionCreatedBy {\n");
    sb.append("    kind: ").append(toIndentedString(kind)).append("\n");
    sb.append("    idReference: ").append(toIndentedString(idReference)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("kind");
    openapiFields.add("id_reference");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 
  public static boolean validate = false;
    public static Predicate<JsonElement> isValid = jsonElement -> true;
    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (!isValid.test(jsonElement)) throw new RuntimeException();
      if (!validate) return;

      if (jsonElement == null) {
        if (!AdminActionCreatedBy.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in AdminActionCreatedBy is not found in the empty JSON string", AdminActionCreatedBy.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!AdminActionCreatedBy.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `AdminActionCreatedBy` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // validate the optional field `kind`
      if (jsonObj.get("kind") != null && !jsonObj.get("kind").isJsonNull()) {
        AdminActionCreatedByKind.validateJsonElement(jsonObj.get("kind"));
      }
      if ((jsonObj.get("id_reference") != null && !jsonObj.get("id_reference").isJsonNull()) && !jsonObj.get("id_reference").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `id_reference` to be a primitive type in the JSON string but got `%s`", jsonObj.get("id_reference").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!AdminActionCreatedBy.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'AdminActionCreatedBy' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<AdminActionCreatedBy> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(AdminActionCreatedBy.class));

       return (TypeAdapter<T>) new TypeAdapter<AdminActionCreatedBy>() {
           @Override
           public void write(JsonWriter out, AdminActionCreatedBy value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public AdminActionCreatedBy read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of AdminActionCreatedBy given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of AdminActionCreatedBy
  * @throws IOException if the JSON string is invalid with respect to AdminActionCreatedBy
  */
  public static AdminActionCreatedBy fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, AdminActionCreatedBy.class);
  }

 /**
  * Convert an instance of AdminActionCreatedBy to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

