/*
 * Broker API
 * Open brokerage accounts, enable stock, options and crypto trading. Manage the ongoing user experience and brokerage customer lifecycle with the Alpaca Broker API
 *
 * The version of the OpenAPI document: 1.1.1
 * Contact: support@alpaca.markets
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package net.jacobpeterson.alpaca.openapi.broker.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.function.Predicate;
import java.time.OffsetDateTime;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.function.Predicate;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import net.jacobpeterson.alpaca.openapi.broker.JSON;

/**
 * GetV1AccountsPositions200Response
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-03-23T18:58:47.485165-07:00[America/Los_Angeles]")
public class GetV1AccountsPositions200Response {
  public static final String SERIALIZED_NAME_AS_OF = "as_of";
  @SerializedName(SERIALIZED_NAME_AS_OF)
  private OffsetDateTime asOf;

  public static final String SERIALIZED_NAME_POSITIONS = "positions";
  @SerializedName(SERIALIZED_NAME_POSITIONS)
  private Object positions;

  public GetV1AccountsPositions200Response() {
  }

  public GetV1AccountsPositions200Response asOf(OffsetDateTime asOf) {
    this.asOf = asOf;
    return this;
  }

   /**
   * Get asOf
   * @return asOf
  **/
  @javax.annotation.Nullable
  public OffsetDateTime getAsOf() {
    return asOf;
  }

  public void setAsOf(OffsetDateTime asOf) {
    this.asOf = asOf;
  }


  public GetV1AccountsPositions200Response positions(Object positions) {
    this.positions = positions;
    return this;
  }

   /**
   * Get positions
   * @return positions
  **/
  @javax.annotation.Nullable
  public Object getPositions() {
    return positions;
  }

  public void setPositions(Object positions) {
    this.positions = positions;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetV1AccountsPositions200Response getV1AccountsPositions200Response = (GetV1AccountsPositions200Response) o;
    return Objects.equals(this.asOf, getV1AccountsPositions200Response.asOf) &&
        Objects.equals(this.positions, getV1AccountsPositions200Response.positions);
  }

  @Override
  public int hashCode() {
    return Objects.hash(asOf, positions);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetV1AccountsPositions200Response {\n");
    sb.append("    asOf: ").append(toIndentedString(asOf)).append("\n");
    sb.append("    positions: ").append(toIndentedString(positions)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("as_of");
    openapiFields.add("positions");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 
  public static boolean validate = false;
    public static Predicate<JsonElement> isValid = jsonElement -> true;
    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (!isValid.test(jsonElement)) throw new RuntimeException();
      if (!validate) return;

      if (jsonElement == null) {
        if (!GetV1AccountsPositions200Response.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in GetV1AccountsPositions200Response is not found in the empty JSON string", GetV1AccountsPositions200Response.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!GetV1AccountsPositions200Response.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `GetV1AccountsPositions200Response` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!GetV1AccountsPositions200Response.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'GetV1AccountsPositions200Response' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<GetV1AccountsPositions200Response> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(GetV1AccountsPositions200Response.class));

       return (TypeAdapter<T>) new TypeAdapter<GetV1AccountsPositions200Response>() {
           @Override
           public void write(JsonWriter out, GetV1AccountsPositions200Response value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public GetV1AccountsPositions200Response read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of GetV1AccountsPositions200Response given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of GetV1AccountsPositions200Response
  * @throws IOException if the JSON string is invalid with respect to GetV1AccountsPositions200Response
  */
  public static GetV1AccountsPositions200Response fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, GetV1AccountsPositions200Response.class);
  }

 /**
  * Convert an instance of GetV1AccountsPositions200Response to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

