/*
 * Broker API
 * Open brokerage accounts, enable stock, options and crypto trading. Manage the ongoing user experience and brokerage customer lifecycle with the Alpaca Broker API
 *
 * The version of the OpenAPI document: 1.1.1
 * Contact: support@alpaca.markets
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package net.jacobpeterson.alpaca.openapi.broker.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.function.Predicate;
import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.UUID;
import org.openapitools.jackson.nullable.JsonNullable;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.function.Predicate;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import net.jacobpeterson.alpaca.openapi.broker.JSON;

/**
 * PDTStatus
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-03-23T18:58:47.485165-07:00[America/Los_Angeles]")
public class PDTStatus {
  public static final String SERIALIZED_NAME_ACCOUNT_ID = "account_id";
  @SerializedName(SERIALIZED_NAME_ACCOUNT_ID)
  private UUID accountId;

  public static final String SERIALIZED_NAME_PDT = "pdt";
  @SerializedName(SERIALIZED_NAME_PDT)
  private Boolean pdt;

  public static final String SERIALIZED_NAME_PDT_REMOVED = "pdt_removed";
  @SerializedName(SERIALIZED_NAME_PDT_REMOVED)
  private Boolean pdtRemoved;

  public static final String SERIALIZED_NAME_PDT_REMOVED_AT = "pdt_removed_at";
  @SerializedName(SERIALIZED_NAME_PDT_REMOVED_AT)
  private OffsetDateTime pdtRemovedAt;

  public PDTStatus() {
  }

  public PDTStatus accountId(UUID accountId) {
    this.accountId = accountId;
    return this;
  }

   /**
   * Account ID
   * @return accountId
  **/
  @javax.annotation.Nullable
  public UUID getAccountId() {
    return accountId;
  }

  public void setAccountId(UUID accountId) {
    this.accountId = accountId;
  }


  public PDTStatus pdt(Boolean pdt) {
    this.pdt = pdt;
    return this;
  }

   /**
   * Account is currently flagged as Pattern Day Trader
   * @return pdt
  **/
  @javax.annotation.Nullable
  public Boolean getPdt() {
    return pdt;
  }

  public void setPdt(Boolean pdt) {
    this.pdt = pdt;
  }


  public PDTStatus pdtRemoved(Boolean pdtRemoved) {
    this.pdtRemoved = pdtRemoved;
    return this;
  }

   /**
   * The account has previously utilized its one-time PDT removal entitlement, and is not allowed to submit any further removal requests
   * @return pdtRemoved
  **/
  @javax.annotation.Nullable
  public Boolean getPdtRemoved() {
    return pdtRemoved;
  }

  public void setPdtRemoved(Boolean pdtRemoved) {
    this.pdtRemoved = pdtRemoved;
  }


  public PDTStatus pdtRemovedAt(OffsetDateTime pdtRemovedAt) {
    this.pdtRemovedAt = pdtRemovedAt;
    return this;
  }

   /**
   * Date and time when PDT was removed for the account. Null if PDT flag has never been lifted.
   * @return pdtRemovedAt
  **/
  @javax.annotation.Nullable
  public OffsetDateTime getPdtRemovedAt() {
    return pdtRemovedAt;
  }

  public void setPdtRemovedAt(OffsetDateTime pdtRemovedAt) {
    this.pdtRemovedAt = pdtRemovedAt;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PDTStatus pdTStatus = (PDTStatus) o;
    return Objects.equals(this.accountId, pdTStatus.accountId) &&
        Objects.equals(this.pdt, pdTStatus.pdt) &&
        Objects.equals(this.pdtRemoved, pdTStatus.pdtRemoved) &&
        Objects.equals(this.pdtRemovedAt, pdTStatus.pdtRemovedAt);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(accountId, pdt, pdtRemoved, pdtRemovedAt);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PDTStatus {\n");
    sb.append("    accountId: ").append(toIndentedString(accountId)).append("\n");
    sb.append("    pdt: ").append(toIndentedString(pdt)).append("\n");
    sb.append("    pdtRemoved: ").append(toIndentedString(pdtRemoved)).append("\n");
    sb.append("    pdtRemovedAt: ").append(toIndentedString(pdtRemovedAt)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("account_id");
    openapiFields.add("pdt");
    openapiFields.add("pdt_removed");
    openapiFields.add("pdt_removed_at");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 
  public static boolean validate = false;
    public static Predicate<JsonElement> isValid = jsonElement -> true;
    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (!isValid.test(jsonElement)) throw new RuntimeException();
      if (!validate) return;

      if (jsonElement == null) {
        if (!PDTStatus.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in PDTStatus is not found in the empty JSON string", PDTStatus.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!PDTStatus.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `PDTStatus` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("account_id") != null && !jsonObj.get("account_id").isJsonNull()) && !jsonObj.get("account_id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `account_id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("account_id").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!PDTStatus.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'PDTStatus' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<PDTStatus> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(PDTStatus.class));

       return (TypeAdapter<T>) new TypeAdapter<PDTStatus>() {
           @Override
           public void write(JsonWriter out, PDTStatus value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public PDTStatus read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of PDTStatus given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of PDTStatus
  * @throws IOException if the JSON string is invalid with respect to PDTStatus
  */
  public static PDTStatus fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, PDTStatus.class);
  }

 /**
  * Convert an instance of PDTStatus to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

