/*
 * Broker API
 * Open brokerage accounts, enable stock, options and crypto trading. Manage the ongoing user experience and brokerage customer lifecycle with the Alpaca Broker API
 *
 * The version of the OpenAPI document: 1.1.1
 * Contact: support@alpaca.markets
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package net.jacobpeterson.alpaca.openapi.broker.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.function.Predicate;
import java.math.BigDecimal;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.function.Predicate;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import net.jacobpeterson.alpaca.openapi.broker.JSON;

/**
 * Account balances in USD.
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-03-23T18:58:47.485165-07:00[America/Los_Angeles]")
public class USDBalances {
  public static final String SERIALIZED_NAME_BUYING_POWER = "buying_power";
  @SerializedName(SERIALIZED_NAME_BUYING_POWER)
  private BigDecimal buyingPower;

  public static final String SERIALIZED_NAME_REGT_BUYING_POWER = "regt_buying_power";
  @SerializedName(SERIALIZED_NAME_REGT_BUYING_POWER)
  private BigDecimal regtBuyingPower;

  public static final String SERIALIZED_NAME_DAYTRADING_BUYING_POWER = "daytrading_buying_power";
  @SerializedName(SERIALIZED_NAME_DAYTRADING_BUYING_POWER)
  private BigDecimal daytradingBuyingPower;

  public static final String SERIALIZED_NAME_OPTIONS_BUYING_POWER = "options_buying_power";
  @SerializedName(SERIALIZED_NAME_OPTIONS_BUYING_POWER)
  private BigDecimal optionsBuyingPower;

  public static final String SERIALIZED_NAME_CASH = "cash";
  @SerializedName(SERIALIZED_NAME_CASH)
  private BigDecimal cash;

  public static final String SERIALIZED_NAME_CASH_WITHDRAWABLE = "cash_withdrawable";
  @SerializedName(SERIALIZED_NAME_CASH_WITHDRAWABLE)
  private BigDecimal cashWithdrawable;

  public static final String SERIALIZED_NAME_CASH_TRANSFERABLE = "cash_transferable";
  @SerializedName(SERIALIZED_NAME_CASH_TRANSFERABLE)
  private BigDecimal cashTransferable;

  public static final String SERIALIZED_NAME_PENDING_TRANSFER_OUT = "pending_transfer_out";
  @SerializedName(SERIALIZED_NAME_PENDING_TRANSFER_OUT)
  private BigDecimal pendingTransferOut;

  public static final String SERIALIZED_NAME_PORTFOLIO_VALUE = "portfolio_value";
  @SerializedName(SERIALIZED_NAME_PORTFOLIO_VALUE)
  private BigDecimal portfolioValue;

  public static final String SERIALIZED_NAME_EQUITY = "equity";
  @SerializedName(SERIALIZED_NAME_EQUITY)
  private BigDecimal equity;

  public static final String SERIALIZED_NAME_LONG_MARKET_VALUE = "long_market_value";
  @SerializedName(SERIALIZED_NAME_LONG_MARKET_VALUE)
  private BigDecimal longMarketValue;

  public static final String SERIALIZED_NAME_SHORT_MARKET_VALUE = "short_market_value";
  @SerializedName(SERIALIZED_NAME_SHORT_MARKET_VALUE)
  private BigDecimal shortMarketValue;

  public static final String SERIALIZED_NAME_INITIAL_MARGIN = "initial_margin";
  @SerializedName(SERIALIZED_NAME_INITIAL_MARGIN)
  private BigDecimal initialMargin;

  public static final String SERIALIZED_NAME_MAINTENANCE_MARGIN = "maintenance_margin";
  @SerializedName(SERIALIZED_NAME_MAINTENANCE_MARGIN)
  private BigDecimal maintenanceMargin;

  public static final String SERIALIZED_NAME_LAST_MAINTENANCE_MARGIN = "last_maintenance_margin";
  @SerializedName(SERIALIZED_NAME_LAST_MAINTENANCE_MARGIN)
  private BigDecimal lastMaintenanceMargin;

  public static final String SERIALIZED_NAME_SMA = "sma";
  @SerializedName(SERIALIZED_NAME_SMA)
  private BigDecimal sma;

  public static final String SERIALIZED_NAME_LAST_EQUITY = "last_equity";
  @SerializedName(SERIALIZED_NAME_LAST_EQUITY)
  private BigDecimal lastEquity;

  public static final String SERIALIZED_NAME_LAST_LONG_MARKET_VALUE = "last_long_market_value";
  @SerializedName(SERIALIZED_NAME_LAST_LONG_MARKET_VALUE)
  private BigDecimal lastLongMarketValue;

  public static final String SERIALIZED_NAME_LAST_SHORT_MARKET_VALUE = "last_short_market_value";
  @SerializedName(SERIALIZED_NAME_LAST_SHORT_MARKET_VALUE)
  private BigDecimal lastShortMarketValue;

  public static final String SERIALIZED_NAME_LAST_CASH = "last_cash";
  @SerializedName(SERIALIZED_NAME_LAST_CASH)
  private BigDecimal lastCash;

  public static final String SERIALIZED_NAME_LAST_BUYING_POWER = "last_buying_power";
  @SerializedName(SERIALIZED_NAME_LAST_BUYING_POWER)
  private BigDecimal lastBuyingPower;

  public static final String SERIALIZED_NAME_LAST_REGT_BUYING_POWER = "last_regt_buying_power";
  @SerializedName(SERIALIZED_NAME_LAST_REGT_BUYING_POWER)
  private BigDecimal lastRegtBuyingPower;

  public static final String SERIALIZED_NAME_LAST_DAYTRADING_BUYING_POWER = "last_daytrading_buying_power";
  @SerializedName(SERIALIZED_NAME_LAST_DAYTRADING_BUYING_POWER)
  private String lastDaytradingBuyingPower;

  public static final String SERIALIZED_NAME_LAST_OPTIONS_BUYING_POWER = "last_options_buying_power";
  @SerializedName(SERIALIZED_NAME_LAST_OPTIONS_BUYING_POWER)
  private BigDecimal lastOptionsBuyingPower;

  public USDBalances() {
  }

  public USDBalances buyingPower(BigDecimal buyingPower) {
    this.buyingPower = buyingPower;
    return this;
  }

   /**
   * Get buyingPower
   * @return buyingPower
  **/
  @javax.annotation.Nullable
  public BigDecimal getBuyingPower() {
    return buyingPower;
  }

  public void setBuyingPower(BigDecimal buyingPower) {
    this.buyingPower = buyingPower;
  }


  public USDBalances regtBuyingPower(BigDecimal regtBuyingPower) {
    this.regtBuyingPower = regtBuyingPower;
    return this;
  }

   /**
   * Get regtBuyingPower
   * @return regtBuyingPower
  **/
  @javax.annotation.Nullable
  public BigDecimal getRegtBuyingPower() {
    return regtBuyingPower;
  }

  public void setRegtBuyingPower(BigDecimal regtBuyingPower) {
    this.regtBuyingPower = regtBuyingPower;
  }


  public USDBalances daytradingBuyingPower(BigDecimal daytradingBuyingPower) {
    this.daytradingBuyingPower = daytradingBuyingPower;
    return this;
  }

   /**
   * Get daytradingBuyingPower
   * @return daytradingBuyingPower
  **/
  @javax.annotation.Nullable
  public BigDecimal getDaytradingBuyingPower() {
    return daytradingBuyingPower;
  }

  public void setDaytradingBuyingPower(BigDecimal daytradingBuyingPower) {
    this.daytradingBuyingPower = daytradingBuyingPower;
  }


  public USDBalances optionsBuyingPower(BigDecimal optionsBuyingPower) {
    this.optionsBuyingPower = optionsBuyingPower;
    return this;
  }

   /**
   * Get optionsBuyingPower
   * @return optionsBuyingPower
  **/
  @javax.annotation.Nullable
  public BigDecimal getOptionsBuyingPower() {
    return optionsBuyingPower;
  }

  public void setOptionsBuyingPower(BigDecimal optionsBuyingPower) {
    this.optionsBuyingPower = optionsBuyingPower;
  }


  public USDBalances cash(BigDecimal cash) {
    this.cash = cash;
    return this;
  }

   /**
   * Get cash
   * @return cash
  **/
  @javax.annotation.Nullable
  public BigDecimal getCash() {
    return cash;
  }

  public void setCash(BigDecimal cash) {
    this.cash = cash;
  }


  public USDBalances cashWithdrawable(BigDecimal cashWithdrawable) {
    this.cashWithdrawable = cashWithdrawable;
    return this;
  }

   /**
   * Get cashWithdrawable
   * @return cashWithdrawable
  **/
  @javax.annotation.Nullable
  public BigDecimal getCashWithdrawable() {
    return cashWithdrawable;
  }

  public void setCashWithdrawable(BigDecimal cashWithdrawable) {
    this.cashWithdrawable = cashWithdrawable;
  }


  public USDBalances cashTransferable(BigDecimal cashTransferable) {
    this.cashTransferable = cashTransferable;
    return this;
  }

   /**
   * Get cashTransferable
   * @return cashTransferable
  **/
  @javax.annotation.Nullable
  public BigDecimal getCashTransferable() {
    return cashTransferable;
  }

  public void setCashTransferable(BigDecimal cashTransferable) {
    this.cashTransferable = cashTransferable;
  }


  public USDBalances pendingTransferOut(BigDecimal pendingTransferOut) {
    this.pendingTransferOut = pendingTransferOut;
    return this;
  }

   /**
   * Get pendingTransferOut
   * @return pendingTransferOut
  **/
  @javax.annotation.Nullable
  public BigDecimal getPendingTransferOut() {
    return pendingTransferOut;
  }

  public void setPendingTransferOut(BigDecimal pendingTransferOut) {
    this.pendingTransferOut = pendingTransferOut;
  }


  public USDBalances portfolioValue(BigDecimal portfolioValue) {
    this.portfolioValue = portfolioValue;
    return this;
  }

   /**
   * Get portfolioValue
   * @return portfolioValue
  **/
  @javax.annotation.Nullable
  public BigDecimal getPortfolioValue() {
    return portfolioValue;
  }

  public void setPortfolioValue(BigDecimal portfolioValue) {
    this.portfolioValue = portfolioValue;
  }


  public USDBalances equity(BigDecimal equity) {
    this.equity = equity;
    return this;
  }

   /**
   * Get equity
   * @return equity
  **/
  @javax.annotation.Nullable
  public BigDecimal getEquity() {
    return equity;
  }

  public void setEquity(BigDecimal equity) {
    this.equity = equity;
  }


  public USDBalances longMarketValue(BigDecimal longMarketValue) {
    this.longMarketValue = longMarketValue;
    return this;
  }

   /**
   * Get longMarketValue
   * @return longMarketValue
  **/
  @javax.annotation.Nullable
  public BigDecimal getLongMarketValue() {
    return longMarketValue;
  }

  public void setLongMarketValue(BigDecimal longMarketValue) {
    this.longMarketValue = longMarketValue;
  }


  public USDBalances shortMarketValue(BigDecimal shortMarketValue) {
    this.shortMarketValue = shortMarketValue;
    return this;
  }

   /**
   * Get shortMarketValue
   * @return shortMarketValue
  **/
  @javax.annotation.Nullable
  public BigDecimal getShortMarketValue() {
    return shortMarketValue;
  }

  public void setShortMarketValue(BigDecimal shortMarketValue) {
    this.shortMarketValue = shortMarketValue;
  }


  public USDBalances initialMargin(BigDecimal initialMargin) {
    this.initialMargin = initialMargin;
    return this;
  }

   /**
   * Get initialMargin
   * @return initialMargin
  **/
  @javax.annotation.Nullable
  public BigDecimal getInitialMargin() {
    return initialMargin;
  }

  public void setInitialMargin(BigDecimal initialMargin) {
    this.initialMargin = initialMargin;
  }


  public USDBalances maintenanceMargin(BigDecimal maintenanceMargin) {
    this.maintenanceMargin = maintenanceMargin;
    return this;
  }

   /**
   * Get maintenanceMargin
   * @return maintenanceMargin
  **/
  @javax.annotation.Nullable
  public BigDecimal getMaintenanceMargin() {
    return maintenanceMargin;
  }

  public void setMaintenanceMargin(BigDecimal maintenanceMargin) {
    this.maintenanceMargin = maintenanceMargin;
  }


  public USDBalances lastMaintenanceMargin(BigDecimal lastMaintenanceMargin) {
    this.lastMaintenanceMargin = lastMaintenanceMargin;
    return this;
  }

   /**
   * Get lastMaintenanceMargin
   * @return lastMaintenanceMargin
  **/
  @javax.annotation.Nullable
  public BigDecimal getLastMaintenanceMargin() {
    return lastMaintenanceMargin;
  }

  public void setLastMaintenanceMargin(BigDecimal lastMaintenanceMargin) {
    this.lastMaintenanceMargin = lastMaintenanceMargin;
  }


  public USDBalances sma(BigDecimal sma) {
    this.sma = sma;
    return this;
  }

   /**
   * Get sma
   * @return sma
  **/
  @javax.annotation.Nullable
  public BigDecimal getSma() {
    return sma;
  }

  public void setSma(BigDecimal sma) {
    this.sma = sma;
  }


  public USDBalances lastEquity(BigDecimal lastEquity) {
    this.lastEquity = lastEquity;
    return this;
  }

   /**
   * Get lastEquity
   * @return lastEquity
  **/
  @javax.annotation.Nullable
  public BigDecimal getLastEquity() {
    return lastEquity;
  }

  public void setLastEquity(BigDecimal lastEquity) {
    this.lastEquity = lastEquity;
  }


  public USDBalances lastLongMarketValue(BigDecimal lastLongMarketValue) {
    this.lastLongMarketValue = lastLongMarketValue;
    return this;
  }

   /**
   * Get lastLongMarketValue
   * @return lastLongMarketValue
  **/
  @javax.annotation.Nullable
  public BigDecimal getLastLongMarketValue() {
    return lastLongMarketValue;
  }

  public void setLastLongMarketValue(BigDecimal lastLongMarketValue) {
    this.lastLongMarketValue = lastLongMarketValue;
  }


  public USDBalances lastShortMarketValue(BigDecimal lastShortMarketValue) {
    this.lastShortMarketValue = lastShortMarketValue;
    return this;
  }

   /**
   * Get lastShortMarketValue
   * @return lastShortMarketValue
  **/
  @javax.annotation.Nullable
  public BigDecimal getLastShortMarketValue() {
    return lastShortMarketValue;
  }

  public void setLastShortMarketValue(BigDecimal lastShortMarketValue) {
    this.lastShortMarketValue = lastShortMarketValue;
  }


  public USDBalances lastCash(BigDecimal lastCash) {
    this.lastCash = lastCash;
    return this;
  }

   /**
   * Get lastCash
   * @return lastCash
  **/
  @javax.annotation.Nullable
  public BigDecimal getLastCash() {
    return lastCash;
  }

  public void setLastCash(BigDecimal lastCash) {
    this.lastCash = lastCash;
  }


  public USDBalances lastBuyingPower(BigDecimal lastBuyingPower) {
    this.lastBuyingPower = lastBuyingPower;
    return this;
  }

   /**
   * Get lastBuyingPower
   * @return lastBuyingPower
  **/
  @javax.annotation.Nullable
  public BigDecimal getLastBuyingPower() {
    return lastBuyingPower;
  }

  public void setLastBuyingPower(BigDecimal lastBuyingPower) {
    this.lastBuyingPower = lastBuyingPower;
  }


  public USDBalances lastRegtBuyingPower(BigDecimal lastRegtBuyingPower) {
    this.lastRegtBuyingPower = lastRegtBuyingPower;
    return this;
  }

   /**
   * Get lastRegtBuyingPower
   * @return lastRegtBuyingPower
  **/
  @javax.annotation.Nullable
  public BigDecimal getLastRegtBuyingPower() {
    return lastRegtBuyingPower;
  }

  public void setLastRegtBuyingPower(BigDecimal lastRegtBuyingPower) {
    this.lastRegtBuyingPower = lastRegtBuyingPower;
  }


  public USDBalances lastDaytradingBuyingPower(String lastDaytradingBuyingPower) {
    this.lastDaytradingBuyingPower = lastDaytradingBuyingPower;
    return this;
  }

   /**
   * Get lastDaytradingBuyingPower
   * @return lastDaytradingBuyingPower
  **/
  @javax.annotation.Nullable
  public String getLastDaytradingBuyingPower() {
    return lastDaytradingBuyingPower;
  }

  public void setLastDaytradingBuyingPower(String lastDaytradingBuyingPower) {
    this.lastDaytradingBuyingPower = lastDaytradingBuyingPower;
  }


  public USDBalances lastOptionsBuyingPower(BigDecimal lastOptionsBuyingPower) {
    this.lastOptionsBuyingPower = lastOptionsBuyingPower;
    return this;
  }

   /**
   * Get lastOptionsBuyingPower
   * @return lastOptionsBuyingPower
  **/
  @javax.annotation.Nullable
  public BigDecimal getLastOptionsBuyingPower() {
    return lastOptionsBuyingPower;
  }

  public void setLastOptionsBuyingPower(BigDecimal lastOptionsBuyingPower) {
    this.lastOptionsBuyingPower = lastOptionsBuyingPower;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    USDBalances usDBalances = (USDBalances) o;
    return Objects.equals(this.buyingPower, usDBalances.buyingPower) &&
        Objects.equals(this.regtBuyingPower, usDBalances.regtBuyingPower) &&
        Objects.equals(this.daytradingBuyingPower, usDBalances.daytradingBuyingPower) &&
        Objects.equals(this.optionsBuyingPower, usDBalances.optionsBuyingPower) &&
        Objects.equals(this.cash, usDBalances.cash) &&
        Objects.equals(this.cashWithdrawable, usDBalances.cashWithdrawable) &&
        Objects.equals(this.cashTransferable, usDBalances.cashTransferable) &&
        Objects.equals(this.pendingTransferOut, usDBalances.pendingTransferOut) &&
        Objects.equals(this.portfolioValue, usDBalances.portfolioValue) &&
        Objects.equals(this.equity, usDBalances.equity) &&
        Objects.equals(this.longMarketValue, usDBalances.longMarketValue) &&
        Objects.equals(this.shortMarketValue, usDBalances.shortMarketValue) &&
        Objects.equals(this.initialMargin, usDBalances.initialMargin) &&
        Objects.equals(this.maintenanceMargin, usDBalances.maintenanceMargin) &&
        Objects.equals(this.lastMaintenanceMargin, usDBalances.lastMaintenanceMargin) &&
        Objects.equals(this.sma, usDBalances.sma) &&
        Objects.equals(this.lastEquity, usDBalances.lastEquity) &&
        Objects.equals(this.lastLongMarketValue, usDBalances.lastLongMarketValue) &&
        Objects.equals(this.lastShortMarketValue, usDBalances.lastShortMarketValue) &&
        Objects.equals(this.lastCash, usDBalances.lastCash) &&
        Objects.equals(this.lastBuyingPower, usDBalances.lastBuyingPower) &&
        Objects.equals(this.lastRegtBuyingPower, usDBalances.lastRegtBuyingPower) &&
        Objects.equals(this.lastDaytradingBuyingPower, usDBalances.lastDaytradingBuyingPower) &&
        Objects.equals(this.lastOptionsBuyingPower, usDBalances.lastOptionsBuyingPower);
  }

  @Override
  public int hashCode() {
    return Objects.hash(buyingPower, regtBuyingPower, daytradingBuyingPower, optionsBuyingPower, cash, cashWithdrawable, cashTransferable, pendingTransferOut, portfolioValue, equity, longMarketValue, shortMarketValue, initialMargin, maintenanceMargin, lastMaintenanceMargin, sma, lastEquity, lastLongMarketValue, lastShortMarketValue, lastCash, lastBuyingPower, lastRegtBuyingPower, lastDaytradingBuyingPower, lastOptionsBuyingPower);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class USDBalances {\n");
    sb.append("    buyingPower: ").append(toIndentedString(buyingPower)).append("\n");
    sb.append("    regtBuyingPower: ").append(toIndentedString(regtBuyingPower)).append("\n");
    sb.append("    daytradingBuyingPower: ").append(toIndentedString(daytradingBuyingPower)).append("\n");
    sb.append("    optionsBuyingPower: ").append(toIndentedString(optionsBuyingPower)).append("\n");
    sb.append("    cash: ").append(toIndentedString(cash)).append("\n");
    sb.append("    cashWithdrawable: ").append(toIndentedString(cashWithdrawable)).append("\n");
    sb.append("    cashTransferable: ").append(toIndentedString(cashTransferable)).append("\n");
    sb.append("    pendingTransferOut: ").append(toIndentedString(pendingTransferOut)).append("\n");
    sb.append("    portfolioValue: ").append(toIndentedString(portfolioValue)).append("\n");
    sb.append("    equity: ").append(toIndentedString(equity)).append("\n");
    sb.append("    longMarketValue: ").append(toIndentedString(longMarketValue)).append("\n");
    sb.append("    shortMarketValue: ").append(toIndentedString(shortMarketValue)).append("\n");
    sb.append("    initialMargin: ").append(toIndentedString(initialMargin)).append("\n");
    sb.append("    maintenanceMargin: ").append(toIndentedString(maintenanceMargin)).append("\n");
    sb.append("    lastMaintenanceMargin: ").append(toIndentedString(lastMaintenanceMargin)).append("\n");
    sb.append("    sma: ").append(toIndentedString(sma)).append("\n");
    sb.append("    lastEquity: ").append(toIndentedString(lastEquity)).append("\n");
    sb.append("    lastLongMarketValue: ").append(toIndentedString(lastLongMarketValue)).append("\n");
    sb.append("    lastShortMarketValue: ").append(toIndentedString(lastShortMarketValue)).append("\n");
    sb.append("    lastCash: ").append(toIndentedString(lastCash)).append("\n");
    sb.append("    lastBuyingPower: ").append(toIndentedString(lastBuyingPower)).append("\n");
    sb.append("    lastRegtBuyingPower: ").append(toIndentedString(lastRegtBuyingPower)).append("\n");
    sb.append("    lastDaytradingBuyingPower: ").append(toIndentedString(lastDaytradingBuyingPower)).append("\n");
    sb.append("    lastOptionsBuyingPower: ").append(toIndentedString(lastOptionsBuyingPower)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("buying_power");
    openapiFields.add("regt_buying_power");
    openapiFields.add("daytrading_buying_power");
    openapiFields.add("options_buying_power");
    openapiFields.add("cash");
    openapiFields.add("cash_withdrawable");
    openapiFields.add("cash_transferable");
    openapiFields.add("pending_transfer_out");
    openapiFields.add("portfolio_value");
    openapiFields.add("equity");
    openapiFields.add("long_market_value");
    openapiFields.add("short_market_value");
    openapiFields.add("initial_margin");
    openapiFields.add("maintenance_margin");
    openapiFields.add("last_maintenance_margin");
    openapiFields.add("sma");
    openapiFields.add("last_equity");
    openapiFields.add("last_long_market_value");
    openapiFields.add("last_short_market_value");
    openapiFields.add("last_cash");
    openapiFields.add("last_buying_power");
    openapiFields.add("last_regt_buying_power");
    openapiFields.add("last_daytrading_buying_power");
    openapiFields.add("last_options_buying_power");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 
  public static boolean validate = false;
    public static Predicate<JsonElement> isValid = jsonElement -> true;
    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (!isValid.test(jsonElement)) throw new RuntimeException();
      if (!validate) return;

      if (jsonElement == null) {
        if (!USDBalances.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in USDBalances is not found in the empty JSON string", USDBalances.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!USDBalances.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `USDBalances` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("buying_power") != null && !jsonObj.get("buying_power").isJsonNull()) && !jsonObj.get("buying_power").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `buying_power` to be a primitive type in the JSON string but got `%s`", jsonObj.get("buying_power").toString()));
      }
      if ((jsonObj.get("regt_buying_power") != null && !jsonObj.get("regt_buying_power").isJsonNull()) && !jsonObj.get("regt_buying_power").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `regt_buying_power` to be a primitive type in the JSON string but got `%s`", jsonObj.get("regt_buying_power").toString()));
      }
      if ((jsonObj.get("daytrading_buying_power") != null && !jsonObj.get("daytrading_buying_power").isJsonNull()) && !jsonObj.get("daytrading_buying_power").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `daytrading_buying_power` to be a primitive type in the JSON string but got `%s`", jsonObj.get("daytrading_buying_power").toString()));
      }
      if ((jsonObj.get("options_buying_power") != null && !jsonObj.get("options_buying_power").isJsonNull()) && !jsonObj.get("options_buying_power").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `options_buying_power` to be a primitive type in the JSON string but got `%s`", jsonObj.get("options_buying_power").toString()));
      }
      if ((jsonObj.get("cash") != null && !jsonObj.get("cash").isJsonNull()) && !jsonObj.get("cash").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `cash` to be a primitive type in the JSON string but got `%s`", jsonObj.get("cash").toString()));
      }
      if ((jsonObj.get("cash_withdrawable") != null && !jsonObj.get("cash_withdrawable").isJsonNull()) && !jsonObj.get("cash_withdrawable").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `cash_withdrawable` to be a primitive type in the JSON string but got `%s`", jsonObj.get("cash_withdrawable").toString()));
      }
      if ((jsonObj.get("cash_transferable") != null && !jsonObj.get("cash_transferable").isJsonNull()) && !jsonObj.get("cash_transferable").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `cash_transferable` to be a primitive type in the JSON string but got `%s`", jsonObj.get("cash_transferable").toString()));
      }
      if ((jsonObj.get("pending_transfer_out") != null && !jsonObj.get("pending_transfer_out").isJsonNull()) && !jsonObj.get("pending_transfer_out").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `pending_transfer_out` to be a primitive type in the JSON string but got `%s`", jsonObj.get("pending_transfer_out").toString()));
      }
      if ((jsonObj.get("portfolio_value") != null && !jsonObj.get("portfolio_value").isJsonNull()) && !jsonObj.get("portfolio_value").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `portfolio_value` to be a primitive type in the JSON string but got `%s`", jsonObj.get("portfolio_value").toString()));
      }
      if ((jsonObj.get("equity") != null && !jsonObj.get("equity").isJsonNull()) && !jsonObj.get("equity").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `equity` to be a primitive type in the JSON string but got `%s`", jsonObj.get("equity").toString()));
      }
      if ((jsonObj.get("long_market_value") != null && !jsonObj.get("long_market_value").isJsonNull()) && !jsonObj.get("long_market_value").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `long_market_value` to be a primitive type in the JSON string but got `%s`", jsonObj.get("long_market_value").toString()));
      }
      if ((jsonObj.get("short_market_value") != null && !jsonObj.get("short_market_value").isJsonNull()) && !jsonObj.get("short_market_value").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `short_market_value` to be a primitive type in the JSON string but got `%s`", jsonObj.get("short_market_value").toString()));
      }
      if ((jsonObj.get("initial_margin") != null && !jsonObj.get("initial_margin").isJsonNull()) && !jsonObj.get("initial_margin").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `initial_margin` to be a primitive type in the JSON string but got `%s`", jsonObj.get("initial_margin").toString()));
      }
      if ((jsonObj.get("maintenance_margin") != null && !jsonObj.get("maintenance_margin").isJsonNull()) && !jsonObj.get("maintenance_margin").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `maintenance_margin` to be a primitive type in the JSON string but got `%s`", jsonObj.get("maintenance_margin").toString()));
      }
      if ((jsonObj.get("last_maintenance_margin") != null && !jsonObj.get("last_maintenance_margin").isJsonNull()) && !jsonObj.get("last_maintenance_margin").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `last_maintenance_margin` to be a primitive type in the JSON string but got `%s`", jsonObj.get("last_maintenance_margin").toString()));
      }
      if ((jsonObj.get("sma") != null && !jsonObj.get("sma").isJsonNull()) && !jsonObj.get("sma").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `sma` to be a primitive type in the JSON string but got `%s`", jsonObj.get("sma").toString()));
      }
      if ((jsonObj.get("last_equity") != null && !jsonObj.get("last_equity").isJsonNull()) && !jsonObj.get("last_equity").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `last_equity` to be a primitive type in the JSON string but got `%s`", jsonObj.get("last_equity").toString()));
      }
      if ((jsonObj.get("last_long_market_value") != null && !jsonObj.get("last_long_market_value").isJsonNull()) && !jsonObj.get("last_long_market_value").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `last_long_market_value` to be a primitive type in the JSON string but got `%s`", jsonObj.get("last_long_market_value").toString()));
      }
      if ((jsonObj.get("last_short_market_value") != null && !jsonObj.get("last_short_market_value").isJsonNull()) && !jsonObj.get("last_short_market_value").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `last_short_market_value` to be a primitive type in the JSON string but got `%s`", jsonObj.get("last_short_market_value").toString()));
      }
      if ((jsonObj.get("last_cash") != null && !jsonObj.get("last_cash").isJsonNull()) && !jsonObj.get("last_cash").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `last_cash` to be a primitive type in the JSON string but got `%s`", jsonObj.get("last_cash").toString()));
      }
      if ((jsonObj.get("last_buying_power") != null && !jsonObj.get("last_buying_power").isJsonNull()) && !jsonObj.get("last_buying_power").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `last_buying_power` to be a primitive type in the JSON string but got `%s`", jsonObj.get("last_buying_power").toString()));
      }
      if ((jsonObj.get("last_regt_buying_power") != null && !jsonObj.get("last_regt_buying_power").isJsonNull()) && !jsonObj.get("last_regt_buying_power").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `last_regt_buying_power` to be a primitive type in the JSON string but got `%s`", jsonObj.get("last_regt_buying_power").toString()));
      }
      if ((jsonObj.get("last_daytrading_buying_power") != null && !jsonObj.get("last_daytrading_buying_power").isJsonNull()) && !jsonObj.get("last_daytrading_buying_power").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `last_daytrading_buying_power` to be a primitive type in the JSON string but got `%s`", jsonObj.get("last_daytrading_buying_power").toString()));
      }
      if ((jsonObj.get("last_options_buying_power") != null && !jsonObj.get("last_options_buying_power").isJsonNull()) && !jsonObj.get("last_options_buying_power").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `last_options_buying_power` to be a primitive type in the JSON string but got `%s`", jsonObj.get("last_options_buying_power").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!USDBalances.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'USDBalances' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<USDBalances> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(USDBalances.class));

       return (TypeAdapter<T>) new TypeAdapter<USDBalances>() {
           @Override
           public void write(JsonWriter out, USDBalances value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public USDBalances read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of USDBalances given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of USDBalances
  * @throws IOException if the JSON string is invalid with respect to USDBalances
  */
  public static USDBalances fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, USDBalances.class);
  }

 /**
  * Convert an instance of USDBalances to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

